"""
Spider — 共享协议常量和消息类型。
"""

# ===== 客户端 → 服务端 =====
REGISTER = "REGISTER"
LOGIN = "LOGIN"
SEND_MSG = "SEND_MSG"
QUERY_PUBKEY = "QUERY_PUBKEY"
STORE_PUBKEY = "STORE_PUBKEY"
COMPROMISED = "COMPROMISED"
ADMIN_AUTH = "ADMIN_AUTH"
ADMIN_CMD = "ADMIN_CMD"
SEARCH_CONTACTS = "SEARCH_CONTACTS"
LOOKUP_USER = "LOOKUP_USER"
CREATE_GROUP = "CREATE_GROUP"
JOIN_GROUP = "JOIN_GROUP"
LEAVE_GROUP = "LEAVE_GROUP"
GROUP_ADD_MEMBER = "GROUP_ADD_MEMBER"
GROUP_REMOVE_MEMBER = "GROUP_REMOVE_MEMBER"
SEND_GROUP_MSG = "SEND_GROUP_MSG"
LIST_MY_GROUPS = "LIST_MY_GROUPS"
GET_GROUP_INFO = "GET_GROUP_INFO"
SEARCH_GROUPS = "SEARCH_GROUPS"
FEDERATE_GROUP = "FEDERATE_GROUP"

# ===== 服务端 → 客户端 =====
RECV_MSG = "RECV_MSG"
OFFLINE_QUEUE = "OFFLINE_QUEUE"
ERROR_MSG = "ERROR"
ADMIN_AUTH_OK = "ADMIN_AUTH_OK"
ADMIN_AUTH_FAIL = "ADMIN_AUTH_FAIL"
CMD_RESULT = "CMD_RESULT"
PING = "PING"
PONG = "PONG"
BROADCAST = "BROADCAST"
RATE_LIMITED = "RATE_LIMITED"
GROUP_EVENT = "GROUP_EVENT"
GROUP_CREATE_RESULT = "GROUP_CREATE_RESULT"
GROUP_LIST_RESULT = "GROUP_LIST_RESULT"
GROUP_INFO_RESULT = "GROUP_INFO_RESULT"
GROUP_SEARCH_RESULT = "GROUP_SEARCH_RESULT"
LOOKUP_USER_RESULT = "LOOKUP_USER_RESULT"

# ===== 跨服务器 =====
RELAY_MSG = "RELAY_MSG"
RELAY_REJECTED = "RELAY_REJECTED"
GROUP_MSG_RELAY = "GROUP_MSG_RELAY"
GROUP_MSG = "GROUP_MSG"
USER_LOOKUP = "USER_LOOKUP"
USER_LOOKUP_RESPONSE = "USER_LOOKUP_RESPONSE"
RATE_LIMIT_QUERY = "RATE_LIMIT_QUERY"
RATE_LIMIT_RESPONSE = "RATE_LIMIT_RESPONSE"

# ===== 回执系统 =====
DELIVERY_RECEIPT = "DELIVERY_RECEIPT"      # 服务器→发送方：消息已送达对方
READ_RECEIPT = "READ_RECEIPT"              # 接收方→发送方：消息已读
SEND_OK = "SEND_OK"                        # 服务端→发送方：服务器已接受消息
READ_RECEIPT_DISABLED = "READ_RECEIPT_DISABLED"  # 服务端→发送方：对方关闭了已读回执

FILE_CHUNK = "FILE_CHUNK"

# ===== 管理员命令 =====
CMD_LIST_ONLINE = "LIST_ONLINE"
CMD_LIST_ALL_USERS = "LIST_ALL_USERS"
CMD_BAN_USER = "BAN_USER"
CMD_UNBAN_USER = "UNBAN_USER"
CMD_KICK_USER = "KICK_USER"
CMD_DELETE_USER = "DELETE_USER"
CMD_CREATE_USER = "CREATE_USER"
CMD_MUTE_USER = "MUTE_USER"
CMD_SET_RATE_LIMIT = "SET_RATE_LIMIT"
CMD_SET_USER_RATE = "SET_USER_RATE"
CMD_SET_MAX_FILE_SIZE = "SET_MAX_FILE_SIZE"
CMD_CLEANUP_FILES = "CLEANUP_FILES"
CMD_DHT_ROUTING_TABLE = "DHT_ROUTING_TABLE"
CMD_DHT_NODE_COUNT = "DHT_NODE_COUNT"
CMD_SET_HIDDEN = "SET_HIDDEN"
CMD_ADD_DHT_WHITELIST = "ADD_DHT_WHITELIST"
CMD_GET_LOGS = "GET_LOGS"
CMD_CONN_STATS = "CONN_STATS"
CMD_BROADCAST_MSG = "BROADCAST_MSG"
CMD_SHUTDOWN = "SHUTDOWN"
CMD_MAINTENANCE_MODE = "MAINTENANCE_MODE"
CMD_SET_MIN_VERSION = "SET_MIN_VERSION"
CMD_RESET_TOFU = "RESET_TOFU"

# ===== 默认端口（均可配置） =====
DEFAULT_TCP_PORT = 7891
DEFAULT_UDP_PORT = 7892
DEFAULT_DHT_PORT = 7893
DEFAULT_INTERSERVER_PORT = 7894
DEFAULT_DIRECT_CONNECT_PORT = 7895
DEFAULT_ONION_PORT = 7896
DEFAULT_ADMIN_PORT = 7897
DEFAULT_BLUETOOTH_PORT = 7898
DEFAULT_WIFI_DIRECT_PORT = 7899

# ===== UI 默认值 =====
DEFAULT_SENT_COLOR = "#FF4444"
DEFAULT_RECV_COLOR = "#44FF44"
DEFAULT_BUTTON_COLOR = "#CC3333"

# ===== 限速默认值 =====
DEFAULT_RATE_LIMIT = 0.5  # 秒/条消息
DEFAULT_BURST_CAPACITY = 10
DEFAULT_MAX_GROUP_SIZE = 100
DEFAULT_MAX_FILE_MB = 100

# ===== 安全参数 =====
REPLAY_WINDOW_SEC = 60

# ===== DHT 参数 =====
DHT_K = 20
DHT_ALPHA = 3
DHT_NODE_ID_BITS = 256

# ===== 用户资料 =====
MIN_DISPLAY_NAME_LEN = 4
MAX_DISPLAY_NAME_LEN = 32

MAX_AVATAR_DIMENSION = 64
MAX_AVATAR_FILE_SIZE = 70 * 1024

# ===== 混淆与洋葱 =====
DEFAULT_OBFUSCATION_MODE = "http"
AVAILABLE_OBFUSCATION_MODES = ["http", "dns", "tls", "websocket", "random"]

DEFAULT_ONION_LAYERS = 3
MAX_ONION_LAYERS = 5
MIN_ONION_LAYERS = 1

# ===== 传输层 =====
TRANSPORT_KEY_ROTATION_SEC = 3600  # 1小时轮换一次

# ===== 直连（Direct Connect）消息类型 =====
DC_HELLO = "DC_HELLO"
DC_AUTH = "DC_AUTH"
DC_SEND_MSG = "DC_SEND_MSG"
DC_RECV_MSG = "DC_RECV_MSG"
DC_FILE_CHUNK = "DC_FILE_CHUNK"
DC_PING = "DC_PING"
DC_PONG = "DC_PONG"
DC_DISCONNECT = "DC_DISCONNECT"
DC_ANNOUNCE = "DC_ANNOUNCE"
DC_NODE_INFO = "DC_NODE_INFO"
DC_RELAY_MSG = "DC_RELAY_MSG"
# 直连网络共享：节点能力通告与流量中继
DC_CAPABILITY = "DC_CAPABILITY"          # 节点网络能力通告（公网/无线电可达性）
DC_NETWORK_RELAY = "DC_NETWORK_RELAY"    # 通过直连网关节点中继公网/无线电流量
DC_ROUTE_QUERY = "DC_ROUTE_QUERY"        # 查询到达某个网络的最短直连路径
DC_ROUTE_RESPONSE = "DC_ROUTE_RESPONSE"  # 直连路径查询应答
# ===== 直连运行参数 =====
MAX_DIRECT_CONNECTIONS = 50
DIRECT_CONNECT_TIMEOUT = 15
BLUETOOTH_SCAN_TIMEOUT = 8
WIFI_DIRECT_SCAN_TIMEOUT = 10
LAN_BROADCAST_INTERVAL = 5
# ===== 软件标识 =====
SOFTWARE_NAME = "Spider"
SOFTWARE_VERSION = "1.0.0"
# ===== 网关（Gateway）自动判定 =====
# 网关节点默认规则：同时具备「公网接入」和「SDR 硬件」时自动成为网关；
# 仅具备其中一项时默认不是网关；两项都具备后自动切换为是。
# 用户可通过 gateway_manual_override 随时手动覆盖（True/False/None=自动）。
GATEWAY_AUTO = "auto"
GATEWAY_FORCE_ENABLED = "enabled"
GATEWAY_FORCE_DISABLED = "disabled"
# ===== 协议版本 =====
PROTOCOL_VERSION = 3
