"""
Spider — 共享协议常量和消息类型。
"""

# ===== 客户端 → 服务端 =====
REGISTER = "REGISTER"
LOGIN = "LOGIN"
SEND_MSG = "SEND_MSG"
QUERY_PUBKEY = "QUERY_PUBKEY"
STORE_PUBKEY = "STORE_PUBKEY"
COMPROMISED = "COMPROMISED"
STORE_DEADMAN_MSG = "STORE_DEADMAN_MSG"
DEADMAN_ACK = "DEADMAN_ACK"
ADMIN_AUTH = "ADMIN_AUTH"
ADMIN_CMD = "ADMIN_CMD"
SEARCH_CONTACTS = "SEARCH_CONTACTS"
LOOKUP_USER = "LOOKUP_USER"
CREATE_GROUP = "CREATE_GROUP"
JOIN_GROUP = "JOIN_GROUP"
LEAVE_GROUP = "LEAVE_GROUP"
GROUP_ADD_MEMBER = "GROUP_ADD_MEMBER"
GROUP_REMOVE_MEMBER = "GROUP_REMOVE_MEMBER"
SEND_GROUP_MSG = "SEND_GROUP_MSG"
LIST_MY_GROUPS = "LIST_MY_GROUPS"
GET_GROUP_INFO = "GET_GROUP_INFO"
SEARCH_GROUPS = "SEARCH_GROUPS"
FEDERATE_GROUP = "FEDERATE_GROUP"

# ===== 服务端 → 客户端 =====
RECV_MSG = "RECV_MSG"
OFFLINE_QUEUE = "OFFLINE_QUEUE"
ERROR_MSG = "ERROR"
ADMIN_AUTH_OK = "ADMIN_AUTH_OK"
ADMIN_AUTH_FAIL = "ADMIN_AUTH_FAIL"
CMD_RESULT = "CMD_RESULT"
PING = "PING"
PONG = "PONG"
BROADCAST = "BROADCAST"
RATE_LIMITED = "RATE_LIMITED"
GROUP_EVENT = "GROUP_EVENT"
GROUP_CREATE_RESULT = "GROUP_CREATE_RESULT"
GROUP_LIST_RESULT = "GROUP_LIST_RESULT"
GROUP_INFO_RESULT = "GROUP_INFO_RESULT"
GROUP_SEARCH_RESULT = "GROUP_SEARCH_RESULT"
LOOKUP_USER_RESULT = "LOOKUP_USER_RESULT"

# ===== 跨服务器 =====
RELAY_MSG = "RELAY_MSG"
RELAY_REJECTED = "RELAY_REJECTED"
GROUP_MSG_RELAY = "GROUP_MSG_RELAY"
GROUP_MSG = "GROUP_MSG"
USER_LOOKUP = "USER_LOOKUP"
USER_LOOKUP_RESPONSE = "USER_LOOKUP_RESPONSE"
RATE_LIMIT_QUERY = "RATE_LIMIT_QUERY"
RATE_LIMIT_RESPONSE = "RATE_LIMIT_RESPONSE"

# ===== 回执系统 =====
DELIVERY_RECEIPT = "DELIVERY_RECEIPT"      # 服务器→发送方：消息已送达对方
READ_RECEIPT = "READ_RECEIPT"              # 接收方→发送方：消息已读
SEND_OK = "SEND_OK"                        # 服务端→发送方：服务器已接受消息
READ_RECEIPT_DISABLED = "READ_RECEIPT_DISABLED"  # 服务端→发送方：对方关闭了已读回执

FILE_CHUNK = "FILE_CHUNK"

# ===== 管理员命令 =====
CMD_LIST_ONLINE = "LIST_ONLINE"
CMD_LIST_ALL_USERS = "LIST_ALL_USERS"
CMD_BAN_USER = "BAN_USER"
CMD_UNBAN_USER = "UNBAN_USER"
CMD_KICK_USER = "KICK_USER"
CMD_DELETE_USER = "DELETE_USER"
CMD_CREATE_USER = "CREATE_USER"
CMD_MUTE_USER = "MUTE_USER"
CMD_SET_RATE_LIMIT = "SET_RATE_LIMIT"
CMD_SET_USER_RATE = "SET_USER_RATE"
CMD_SET_MAX_FILE_SIZE = "SET_MAX_FILE_SIZE"
CMD_CLEANUP_FILES = "CLEANUP_FILES"
CMD_DHT_ROUTING_TABLE = "DHT_ROUTING_TABLE"
CMD_DHT_NODE_COUNT = "DHT_NODE_COUNT"
CMD_SET_HIDDEN = "SET_HIDDEN"
CMD_ADD_DHT_WHITELIST = "ADD_DHT_WHITELIST"
CMD_GET_LOGS = "GET_LOGS"
CMD_CONN_STATS = "CONN_STATS"
CMD_BROADCAST_MSG = "BROADCAST_MSG"
CMD_SHUTDOWN = "SHUTDOWN"
CMD_MAINTENANCE_MODE = "MAINTENANCE_MODE"
CMD_SET_MIN_VERSION = "SET_MIN_VERSION"
CMD_RESET_TOFU = "RESET_TOFU"

# ===== 默认端口（均可配置） =====
DEFAULT_TCP_PORT = 7891
DEFAULT_UDP_PORT = 7892
DEFAULT_DHT_PORT = 7893
DEFAULT_INTERSERVER_PORT = 7894
DEFAULT_DIRECT_CONNECT_PORT = 7895
DEFAULT_ONION_PORT = 7896
DEFAULT_ADMIN_PORT = 7897
DEFAULT_BLUETOOTH_PORT = 7898
DEFAULT_WIFI_DIRECT_PORT = 7899

# ===== UI 默认值 =====
DEFAULT_SENT_COLOR = "#FF4444"
DEFAULT_RECV_COLOR = "#44FF44"
DEFAULT_BUTTON_COLOR = "#CC3333"

# ===== 限速默认值 =====
DEFAULT_RATE_LIMIT = 0.5  # 秒/条消息
DEFAULT_BURST_CAPACITY = 10
DEFAULT_MAX_GROUP_SIZE = 100
DEFAULT_MAX_FILE_MB = 100

# ===== 安全参数 =====
REPLAY_WINDOW_SEC = 60

# ===== DHT 参数 =====
DHT_K = 20
DHT_ALPHA = 3
DHT_NODE_ID_BITS = 256

# ===== 用户资料 =====
MIN_DISPLAY_NAME_LEN = 4
MAX_DISPLAY_NAME_LEN = 32

MAX_AVATAR_DIMENSION = 64
MAX_AVATAR_FILE_SIZE = 70 * 1024

# ===== 混淆与洋葱 =====
DEFAULT_OBFUSCATION_MODE = "http"
AVAILABLE_OBFUSCATION_MODES = ["http", "dns", "tls", "websocket", "random"]

DEFAULT_ONION_LAYERS = 3
MAX_ONION_LAYERS = 5
MIN_ONION_LAYERS = 1

# ===== 传输层 =====
TRANSPORT_KEY_ROTATION_SEC = 3600  # 1小时轮换一次

# ===== 直连（Direct Connect）消息类型 =====
DC_HELLO = "DC_HELLO"
DC_AUTH = "DC_AUTH"
DC_SEND_MSG = "DC_SEND_MSG"
DC_RECV_MSG = "DC_RECV_MSG"
DC_FILE_CHUNK = "DC_FILE_CHUNK"
DC_PING = "DC_PING"
DC_PONG = "DC_PONG"
DC_DISCONNECT = "DC_DISCONNECT"
DC_ANNOUNCE = "DC_ANNOUNCE"
DC_NODE_INFO = "DC_NODE_INFO"
DC_RELAY_MSG = "DC_RELAY_MSG"
# 直连网络共享：节点能力通告与流量中继
DC_CAPABILITY = "DC_CAPABILITY"          # 节点网络能力通告（公网/无线电可达性）
DC_NETWORK_RELAY = "DC_NETWORK_RELAY"    # 通过直连网关节点中继公网/无线电流量
DC_ROUTE_QUERY = "DC_ROUTE_QUERY"        # 查询到达某个网络的最短直连路径
DC_ROUTE_RESPONSE = "DC_ROUTE_RESPONSE"  # 直连路径查询应答
# ===== 直连运行参数 =====
MAX_DIRECT_CONNECTIONS = 50
DIRECT_CONNECT_TIMEOUT = 15
BLUETOOTH_SCAN_TIMEOUT = 8
WIFI_DIRECT_SCAN_TIMEOUT = 10
LAN_BROADCAST_INTERVAL = 5
# ===== 软件标识 =====
SOFTWARE_NAME = "Spider"
SOFTWARE_VERSION = "1.0.0"
# ===== 网关（Gateway）自动判定 =====
# 网关节点默认规则：同时具备「公网接入」和「SDR 硬件」时自动成为网关；
# 仅具备其中一项时默认不是网关；两项都具备后自动切换为是。
# 用户可通过 gateway_manual_override 随时手动覆盖（True/False/None=自动）。
GATEWAY_AUTO = "auto"
GATEWAY_FORCE_ENABLED = "enabled"
GATEWAY_FORCE_DISABLED = "disabled"
# ===== 协议版本 =====
PROTOCOL_VERSION = 3

# ===== 论坛子系统（Forum）=====
# 帖子不端到端加密，明文存服务器，传输走现有 TransportEncryptor
# 帖子 ID 格式：{node_id}:{64hex}

# --- 帖子（POST_）---
POST_CREATE = "POST_CREATE"           # 客户端→服务端：创建帖子
POST_CREATE_RESULT = "POST_CREATE_RESULT"  # 服务端→客户端：创建结果
POST_GET = "POST_GET"                 # 客户端→服务端：按 ID 获取帖子（支持跨服寻址）
POST_GET_RESULT = "POST_GET_RESULT"   # 服务端→客户端：帖子内容
POST_LIST = "POST_LIST"               # 客户端→服务端：获取帖子列表（本服）
POST_LIST_RESULT = "POST_LIST_RESULT" # 服务端→客户端：帖子列表
POST_DELETE = "POST_DELETE"           # 客户端→服务端：删除帖子（作者或管理员）
POST_DELETE_RESULT = "POST_DELETE_RESULT"
POST_EDIT = "POST_EDIT"               # 客户端→服务端：编辑帖子
POST_EDIT_RESULT = "POST_EDIT_RESULT"
POST_SEARCH = "POST_SEARCH"           # 客户端→服务端：搜索帖子（本服）
POST_SEARCH_RESULT = "POST_SEARCH_RESULT"
POST_HOT_RANKING = "POST_HOT_RANKING" # 客户端→服务端：热度排名
POST_HOT_RANKING_RESULT = "POST_HOT_RANKING_RESULT"
POST_WHY_RANKED = "POST_WHY_RANKED"   # 客户端→服务端：为什么这个排名（分解）
POST_WHY_RANKED_RESULT = "POST_WHY_RANKED_RESULT"

# --- 评论（COMMENT_）---
COMMENT_CREATE = "COMMENT_CREATE"
COMMENT_CREATE_RESULT = "COMMENT_CREATE_RESULT"
COMMENT_LIST = "COMMENT_LIST"
COMMENT_LIST_RESULT = "COMMENT_LIST_RESULT"
COMMENT_DELETE = "COMMENT_DELETE"
COMMENT_DELETE_RESULT = "COMMENT_DELETE_RESULT"
COMMENT_EDIT = "COMMENT_EDIT"
COMMENT_EDIT_RESULT = "COMMENT_EDIT_RESULT"

# --- 投票（VOTE_）---
VOTE_CAST = "VOTE_CAST"               # 客户端→服务端：投票（-1/0/1）
VOTE_CAST_RESULT = "VOTE_CAST_RESULT" # 服务端→客户端：投票结果（含新热度）
VOTE_GET = "VOTE_GET"                 # 获取当前用户对某对象的投票
VOTE_GET_RESULT = "VOTE_GET_RESULT"

# --- 服务器卡片（SERVER_）---
SERVER_INFO_REQUEST = "SERVER_INFO_REQUEST"   # 客户端→服务端：请求服务器卡片（无需认证）
SERVER_INFO_RESPONSE = "SERVER_INFO_RESPONSE" # 服务端→客户端：服务器卡片
SERVER_DIRECTORY_QUERY = "SERVER_DIRECTORY_QUERY"     # 查询服务器目录
SERVER_DIRECTORY_RESULT = "SERVER_DIRECTORY_RESULT"
SERVER_DIRECTORY_ANNOUNCE = "SERVER_DIRECTORY_ANNOUNCE" # 服→服：目录条目广播
SERVER_DIRECTORY_FETCH = "SERVER_DIRECTORY_FETCH"     # 服→服：拉取目录
SERVER_KNOWN_HOSTS = "SERVER_KNOWN_HOSTS"             # 客户端→服务端：已知主机列表

# --- 负载与限流（LOAD_）---
LOAD_STATUS = "LOAD_STATUS"               # 服务端→客户端：当前负载状态
LOAD_STATUS_REQUEST = "LOAD_STATUS_REQUEST" # 客户端→服务端：请求负载状态
LOAD_ONLINE_COUNT = "LOAD_ONLINE_COUNT"   # 在线人数（含在 SERVER_INFO_RESPONSE 中）

# --- 跨服寻址（CROSS_SERVER_）---
CROSS_POST_FETCH = "CROSS_POST_FETCH"     # 服→服：按 ID 拉取帖子
CROSS_POST_FETCH_RESULT = "CROSS_POST_FETCH_RESULT"
CROSS_SERVER_LOOKUP = "CROSS_SERVER_LOOKUP" # 服→服：通过 DHT 查找服务器
CROSS_SERVER_LOOKUP_RESULT = "CROSS_SERVER_LOOKUP_RESULT"
CROSS_USER_PROOF = "CROSS_USER_PROOF"       # 服→服：用户存在性证明
CROSS_USER_PROOF_RESULT = "CROSS_USER_PROOF_RESULT"

# --- 通知（NOTIFICATION_）---
NOTIFICATION_LIST = "NOTIFICATION_LIST"
NOTIFICATION_LIST_RESULT = "NOTIFICATION_LIST_RESULT"
NOTIFICATION_MARK_READ = "NOTIFICATION_MARK_READ"
NOTIFICATION_PUSH = "NOTIFICATION_PUSH"     # 服务端→客户端：实时通知推送

# --- 举报与审核（REPORT_）---
REPORT_SUBMIT = "REPORT_SUBMIT"
REPORT_SUBMIT_RESULT = "REPORT_SUBMIT_RESULT"

# --- 草稿（DRAFT_）---
DRAFT_SAVE = "DRAFT_SAVE"
DRAFT_LIST = "DRAFT_LIST"
DRAFT_LIST_RESULT = "DRAFT_LIST_RESULT"
DRAFT_DELETE = "DRAFT_DELETE"

# --- 论坛用户资料（FORUM_PROFILE_）---
FORUM_PROFILE_GET = "FORUM_PROFILE_GET"
FORUM_PROFILE_RESULT = "FORUM_PROFILE_RESULT"
FORUM_PROFILE_BLOCK = "FORUM_PROFILE_BLOCK"
FORUM_PROFILE_UNBLOCK = "FORUM_PROFILE_UNBLOCK"

# ===== 论坛常量 =====
FORUM_POST_ID_HEX_LEN = 64
FORUM_MAX_TITLE_LEN = 128
FORUM_MAX_CONTENT_LEN = 65536
FORUM_MAX_COMMENT_LEN = 4096
FORUM_MAX_TAGS_PER_POST = 5
FORUM_MAX_TAG_LEN = 8
FORUM_DEFAULT_HOT_WEIGHT = 0.8
FORUM_NEW_USER_COOLDOWN_HOURS = 24
FORUM_HEAT_RECALC_INTERVAL_MIN = 5
FORUM_HEAT_RECALC_INTERVAL_MAX = 10
FORUM_CROSS_SERVER_TIMEOUT_SEC = 5
FORUM_DIRECTORY_CACHE_TTL_SEC = 300
FORUM_AUDIT_LOG_RETENTION_DAYS = 30
FORUM_BACKUP_RETENTION_DAYS = 30
FORUM_ARCHIVE_OFFLINE_DAYS = 30

# 负载限流阈值
FORUM_LOAD_SLOW_MESSAGES = 0.5
FORUM_LOAD_SLOW_POSTING = 0.6
FORUM_LOAD_BLOCK_SEARCH = 0.7
FORUM_LOAD_BLOCK_REGISTER = 0.75
FORUM_LOAD_BLOCK_DHT = 0.8
FORUM_LOAD_BLOCK_LOGIN = 0.9
FORUM_LOAD_LOGOUT_USERS = 0.95
FORUM_LOAD_BLOCK_ALL = 1.0
FORUM_LOAD_HYSTERESIS = 0.05

# 热度等级
FORUM_HEAT_LEVEL_GREEN = "green"
FORUM_HEAT_LEVEL_YELLOW = "yellow"
FORUM_HEAT_LEVEL_ORANGE = "orange"
FORUM_HEAT_LEVEL_RED = "red"


# ===== 新增常量（仅追加，不修改已有）=====
# 文件保留期
DEFAULT_FILE_RETENTION_DAYS = 7

# 管理员安全参数
SESSION_TIMEOUT_MIN = 60
MAX_LOGIN_ATTEMPTS = 5
LOCKOUT_SEC = 300

# 管理员命令（commands.py 实际使用、此前缺失的常量）
CMD_REMOVE_DHT_WHITELIST = "REMOVE_DHT_WHITELIST"
CMD_ADD_BOOTSTRAP = "ADD_BOOTSTRAP"
CMD_DHT_DISCONNECT = "DHT_DISCONNECT"
CMD_SET_RATE_BURST = "SET_RATE_BURST"
CMD_RATE_LIMIT_STATUS = "RATE_LIMIT_STATUS"
CMD_SET_FILE_RETENTION = "SET_FILE_RETENTION"
CMD_FILE_STATS = "FILE_STATS"
CMD_SET_FILE_ENABLED = "SET_FILE_ENABLED"
CMD_CHANGE_ADMIN_PIN = "CHANGE_ADMIN_PIN"
CMD_SET_LOG_LEVEL = "SET_LOG_LEVEL"
CMD_FORCE_SHUTDOWN = "FORCE_SHUTDOWN"
CMD_RELOAD_CONFIG = "RELOAD_CONFIG"
CMD_SET_SERVER_NAME = "SET_SERVER_NAME"
CMD_SET_MAX_CONNECTIONS = "SET_MAX_CONNECTIONS"
CMD_SET_MIN_CLIENT_VERSION = "SET_MIN_CLIENT_VERSION"

